#
# Module manifest for module 'PSWriteMessage'
#
# Generated by: William Quinn
#
# Generated on: 8/20/2026
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'PSWriteMessage.psm1'

# Version number of this module. CalVer: YYYY.0M.0D, bumped on each dated release.
ModuleVersion = '2026.08.21'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '5b3bc0dd-6a83-4d1f-8038-b7c940158919'

# Author of this module
Author = 'William Quinn'

# Company or vendor of this module
CompanyName = 'William Quinn'

# Copyright statement for this module
Copyright = '(c) 2024-2026 William Quinn. Licensed under the MIT License.'

# Description of the functionality provided by this module
Description = 'Write-Message is a drop-in replacement for the builtin Write-* cmdlets: it timestamps every message, formats it by type (Debug, Verbose, Info, Success, Warning, Error) with ANSI color and a type prefix, and can optionally tee the message to a log file.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Write-Message'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Logging', 'Console', 'Write-Host', 'ANSI', 'PSStyle'

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/youvegotwq/PSWriteMessage/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/youvegotwq/PSWriteMessage'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = @'
Unreleased

Changed:
- BREAKING: Write-Message no longer writes to the success stream. Output now
  goes to the host via Write-Host (information stream 6), so log lines can no
  longer contaminate a function's return value or a captured pipeline. Callers
  that captured the string ($x = Write-Message ...) now get $null; use 6>&1 or
  -OutFile to capture the text. OutputType is now [void].
- Debug/Verbose messages show for any effective preference other than
  SilentlyContinue (was: only Continue), matching the built-in Write-Verbose /
  Write-Debug. This makes -Debug work on Windows PowerShell 5.1, where the
  switch sets $DebugPreference to Inquire rather than Continue.

Fixed:
- -Verbose / -Debug passed to an ancestor function in another module or script
  is now honored; the effective preference is resolved from the caller's scope
  instead of the module's own.

Full changelog: https://github.com/youvegotwq/PSWriteMessage/blob/main/CHANGELOG.md
'@

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

